openapi: "3.0.3"

info:
  title: Pgenie Service
  version: "1.0"

servers:
  - url: https://pgenie.tech/api/v1

paths:
  /codegen:
    summary: Code generator
    post:
      summary: Process input and generate code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/files"
      responses:
        200:
          description: Generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/files"
        400:
          description: Code generation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message"
        410:
          $ref: "#/components/responses/unsupported"

components:
  responses:
    unsupported:
      description: Unsupported version of API
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/message"

  schemas:
    files:
      type: array
      items:
        type: object
        properties:
          name:
            $ref: "#/components/schemas/path"
          contents:
            type: string
            minLength: 1
            maxLength: 100000
        required:
          - name
          - contents
      minItems: 1
      maxItems: 1000

    path:
      type: string
      minLength: 1
      maxLength: 200

    message:
      type: string
      minLength: 1
      maxLength: 200
