openapi: "3.0.3"

info:
  title: Pgenie API
  version: "1.0"

paths:
  /codegen:
    summary: Code generator
    post:
      summary: Process input and generate code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sourceFiles"
      responses:
        200:
          description: Generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generatedFiles"
        400:
          description: Code generation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message"
        410:
          $ref: "#/components/responses/unsupported"

components:
  responses:
    unsupported:
      description: Unsupported version of API
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/message"

  schemas:
    sourceFiles:
      type: object
      properties:
        project:
          type: string
          minLength: 1
          maxLength: 10000
        migrations:
          $ref: "#/components/schemas/migrationFiles"
        queries:
          $ref: "#/components/schemas/queryFiles"
      required:
        - project
        - migrations
        - queries

    migrationFiles:
      type: array
      items:
        $ref: "#/components/schemas/migrationFile"

    migrationFile:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/path"
        contents:
          type: string
          minLength: 1
          maxLength: 100000
      required:
        - name
        - contents

    queryFiles:
      type: array
      items:
        $ref: "#/components/schemas/queryFile"

    queryFile:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/path"
        contents:
          type: string
          minLength: 1
          maxLength: 100000
      required:
        - name
        - contents

    path:
      type: string
      minLength: 1
      maxLength: 200

    message:
      type: string
      minLength: 1
      maxLength: 200

    generatedFiles:
      type: array
      items:
        type: object
        properties:
          name:
            $ref: "#/components/schemas/path"
          contents:
            type: string
            minLength: 1
            maxLength: 100000
        required:
          - name
          - contents
