name: Generate and deploy artifacts

on:
  push:
    branches:
      - master
      - dev

env:
  NAME: github-actions
  EMAIL: github-actions@pgenie.tech

jobs:

  deploy-client-v1:
    name: Deploy the Haskell client lib
    env:
      DESTINATION: pgenie-tech/api-client-v1
    runs-on: ubuntu-latest
    steps:

      - name: Check out the source code
        uses: actions/checkout@v3.0.2

      - name: Generate code
        uses: craicoverflow/openapi-generator-generate-action@v1.2.1
        with:
          generator: haskell-http-client
          input: v1.openapi.yaml
          output: dist

      - name: Push directory to another repository
        uses: leigholiver/commit-with-deploy-key@v1.0.3
        with:
          source: dist
          destination_repo: ${{ env.DESTINATION }}
          git_username: ${{ env.NAME }}
          git_email: ${{ env.EMAIL }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}

  deploy-server-v1:
    name: Deploy the Haskell server lib
    env:
      DESTINATION: pgenie-tech/api-server-v1
    runs-on: ubuntu-latest
    steps:

      - name: Check out the source code
        uses: actions/checkout@v3.0.2

      - name: Generate code
        uses: craicoverflow/openapi-generator-generate-action@v1.2.1
        with:
          generator: haskell
          input: v1.openapi.yaml
          output: dist

      - name: Push directory to another repository
        uses: leigholiver/commit-with-deploy-key@v1.0.3
        with:
          source: dist
          destination_repo: ${{ env.DESTINATION }}
          git_username: ${{ env.NAME }}
          git_email: ${{ env.EMAIL }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}
